# This is a basic workflow to help you get started with Actions

name: clang-format

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.5
      with:
        # Source folder to check formatting
        source: '.' # optional, default is .
        # Folder to exclude from formatting check
        # exclude: # optional, default is none
        # List of extensions to check
        #extensions: # optional, default is c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx
        # Version of clang-format
        #clangFormatVersion: # optional, default is 9
